// Player-facing changelog — newest first. Single source of truth for BOTH the in-page
// 🗒️ Changelog modal (index.html) AND the Discord changelog post: the GitHub Action posts
// only the entries ADDED in a push (diff vs the previous commit), so Discord == this file.
// One release per date: { date:'YYYY-MM-DD', title:'…', items:['New: …','Fix: …'] }.
// Keep bullets plain-language and about what a PLAYER notices — never kit/test/build/refactor.
window.CHANGELOG = [
  { date: '2026-07-12', title: 'Landscape phones, fixed up 📱', items: [
    'Fix: playing sideways on a phone got a full pass — the Collection store fits again (with a proper progress donut), the quick side drawer opens compact and starts tucked when there\'s no room, and game end screens now show the score card beside the buttons instead of spilling off the screen.',
    'Minesweeper: on sideways phones the DIG/FLAG switch sits on the left edge now, so the minefield uses the whole height — noticeably bigger tiles.',
  ] },
  { date: '2026-07-12', title: 'Every game explains itself 📖', items: [
    'New: every game now has an ℹ️ "How to play" entry in its ☰ menu — what the game is, how it plays, and quick answers: is it free (yes), does it work offline (yes), where do your scores live (on your device). In all 8 languages.',
  ] },
  { date: '2026-07-12', title: 'Welcome gift, free play & shinier bonuses 🎁✨', items: [
    'New: a 🎁 Welcome gift waits at the top of the Collection — claim a one-time 100 🏆 to kick-start your collection with a skin or two.',
    'New: ✨ Free play — a switch at the bottom of the Collection that unlocks every cosmetic to try on and wear, no trophies spent. Flip it off and your real collection and balance are exactly as you left them; titles are still earned by playing.',
    'Change: the ⚡ good-run bonus is now three big bolts that light up as you earn them — in the challenges drawer and the in-game 🏆 panel — instead of a small counter line.',
    'Change: during a run, the quick side menu\'s ‹‹ tab fades to a faint ghost so it can\'t hide anything behind it (looking at you, sneaky snake fruit) — it comes back to full strength on hover and on menu screens.',
  ] },
  { date: '2026-07-12', title: 'SIX new games! 💣🧮🐱🏮🎈🐾', items: [
    'New game: Minesweeper 💣 — the logic classic in a sonar theme. Your first dig is always safe, flags and chording work like you remember, four board sizes from Easy to Expert, and a Relaxed option gives you three hearts before the boom.',
    'New game: 2048 🧮 — slide and merge your way to the fabled tile, then keep going. Classic 4×4 plus Mini 3×3 and Big 5×5 boards, with honey, neon and kraft tile themes in the Collection.',
    'New game: Trap the Cat 🐱 — fence in the wandering cat with rose hedges on a hex garden; fewer hedges, bigger score. The drowsy Kitten mode (it naps mid-chase!) is made for young players, and the premium Ember and Void cats trail real fire and shadow.',
    'New game: Glow Says 🏮 — watch the lanterns light up, then tap the tune back. Chill mode never fails you, Hard adds two lanterns, Expert packs nine in a 3×3 grid.',
    'New game: Balloon Pop 🎈 — happy no-lose popping for the little ones, with colour streaks, confetti, the odd gust of wind and fireworks every 50 pops in Zen. Bees mode dares you NOT to tap the bee.',
    'New game: Critter Match 🐾 — flip the cards and find matching animal pairs. Three board sizes, Pass & Play for 2–4 players on one screen, and a Speedrun mode against the clock.',
    'New: the Collection grew everywhere — new cheap skins for every single game, three game-themed crosshair cursors, and a premium tier: the flaming Ember Cat, the wispy Void Cat and an Obsidian Citadel wreathed in nether-fire.',
    'Fix: the catalogue remembers your filters when you hop into a game and come back.',
  ] },
  { date: '2026-07-11', title: 'Sudoku difficulties, properly spaced 🔢', items: [
    'Fix: Medium played nearly as hard as Hard — boards were dug far past their intended clue count. Every difficulty now keeps a guaranteed range of starting clues (Easy ~36, Medium 30–34, Hard 26–30, Expert 22–26), so the ladder actually climbs step by step.',
    'Change: Medium needs exactly one clever deduction beyond the basics, and the starting board always shows every digit at least once (Easy too) — no more “where are all the ones?” openings.',
    'Change: the Daily puzzle uses the new grading from today onward — still the same board for everyone.',
  ] },
  { date: '2026-07-11', title: 'Forcefield glow-up + your profile in every game 🌐', items: [
    'New: Forcefield looks the part now — the battle station got a proper hull with spinning armor plating, blinking lights and a weapon dish that visibly charges up; shots fire as layered energy bolts with a muzzle flash, a marching targeting line and a lock-on reticle that tightens as the shot nears.',
    'New: Forcefield planet skins now theme the whole battle — pick a world in the Collection and your dome, the charge meter and the station all match it. Plus twinkling stars, the odd shooting star and clouds drifting over the planet.',
    'New: the home page’s quick menu (Profile · Challenges · Collection) now rides along in every game — check your profile or spend trophies without leaving; during a run it tucks behind the ‹‹ tab, and opening it pauses the game.',
    'Change: fullscreen ⛶ is one tap from a game’s top bar now, instead of hiding in the ☰ menu.',
    'Change: pausing looks and works the same everywhere — the frozen game stays visible behind a light “Paused” veil so you can plan your next move, and tapping outside any panel resumes play.',
    'Fix: the mascot’s head sits properly centered in the logo and favicon now.',
  ] },
  { date: '2026-07-10', title: 'Sudoku: correct numbers lock in 🔢', items: [
    'Fix: once you place a correct number in Sudoku, it locks in — no more accidentally clearing or overwriting it (and losing progress) mid-round. Wrong entries stay editable, and Undo still works if you really mean it.',
  ] },
  { date: '2026-07-10', title: 'Menus switch language instantly 🌐', items: [
    'Change: switching the language while a game menu is open now updates it on the spot, in every game — no more stale English (or stale anything) until the next screen.',
  ] },
  { date: '2026-07-09', title: 'New game: Sudoku 🔢', items: [
    'New: Sudoku — fill the 9×9 grid so every row, column and box holds 1–9. Four real difficulties (Easy to Expert, graded by the logic each puzzle actually needs), a Daily puzzle that’s the same for everyone, and a relaxed Zen mode with no timer or strikes.',
    'New: logical hints that teach — tap 💡 and the game highlights where to look and explains the reasoning (never a random reveal), then tap again to apply it.',
    'New: pencil marks, undo, per-digit counters, and unlockable board themes and numeral styles in the Collection.',
    'New: step away anytime — unfinished boards are kept under “In progress” (last 50) so you can pick them up later; and two new digit styles in the Collection: Animals and Shapes.',
  ] },
  { date: '2026-07-09', title: 'A clearer collection bar 🎨', items: [
    'Change: your Collection bar now shows how many skins you’ve unlocked out of the total (like 20 / 90), so it’s clear at a glance how much is left to collect — trophies stay just for buying and titles.',
    'Fix: on shared score cards the game’s mode and difficulty no longer get cut off in languages with longer words — the line shrinks to fit.',
  ] },
  { date: '2026-07-08', title: 'Promote komyo + a friendlier collection bar 🎉', items: [
    'New: a “🎉 Promote” tab in the menu — run a site, blog, app or channel? Embed komyo (or any game) and we’ll feature a link back to you. Reach out and we’ll add you to the list.',
    'Change: your Collection bar now counts the free default skins you already own, so a fresh profile shows a real starting % instead of a flat 0%.',
  ] },
  { date: '2026-07-07', title: 'Music that builds with the action 🎵', items: [
    'New: every game now has richer, produced music that rises and falls with the moment — more enemies, higher speed and bigger stakes bring the beat and extra layers in, then it eases back when things calm down.',
    'New: each game has its own distinct track and mood — no two games share the same tune anymore.',
    'New: Neon Snake’s music is richer and fuller now, and you can unlock an alternate “Neon Banger” take in the Collection (🏆 100).',
    'New: preview any music track in the Collection before you spend on it — tap ▶ to hear it first.',
  ] },
  { date: '2026-07-07', title: 'How the Collection bar works 🎨', items: [
    'Clarification: the Collection bar measures progress by trophies spent against the total cost of every skin — so pricier skins move it more, in proportion to their cost, and a brand-new profile sits at a true 0%.',
  ] },
  { date: '2026-07-07', title: 'Truer collection progress 🎨', items: [
    'Change: your Collection bar now measures trophies spent against the total cost of every skin, instead of counting items — so a brand-new profile starts at a real 0%, and a single pricey unlock no longer jumps the bar.',
  ] },
  { date: '2026-07-07', title: 'Scan-to-play score cards 📇', items: [
    'New: your score card now carries a scan-to-play QR code — point a phone at a shared (or printed) card and it jumps straight into the game.',
    'Fix: the score card shows the mode and difficulty in your language now, instead of always English.',
    'Fix: Forcefield opens the exact mode a shared link points to — the mode/difficulty in the link was being ignored on load.',
  ] },
  { date: '2026-07-06', title: 'Range: snappier aim 🎯', items: [
    'Fix: in Range the crosshair now tracks your mouse instantly instead of trailing a frame behind — aiming feels tight and responsive.',
    'Change: the end screen dropped a confusing extra timing number — it now shows just accuracy, hits and misses.',
  ] },
  { date: '2026-07-06', title: 'Share your run as a card 📤', items: [
    'New: the end-of-game share now leads with your score card — the card shows right there, and one Share button sends the image itself (into any app via your phone\'s share sheet, or copy/download on desktop). No more sharing a plain text line.',
    'Change: the site Share button is now a single button too — it opens your share sheet on mobile (every app) or copies the link on desktop, instead of a row of network icons.',
  ] },
  { date: '2026-07-06', title: 'Frog Bonk: tidier Zen 🐸', items: [
    'Fix: in Frog Bonk\'s Zen mode the difficulty picker is now grayed out — Zen has no failing, so difficulty never did anything there, and the menu now says so instead of offering a dead choice.',
  ] },
  { date: '2026-07-06', title: 'One update to rule them all 🔄', items: [
    'Fix: pressing "Update now" (in Settings or any game\'s ☰ menu) now brings the WHOLE site to the newest version at once — before, a game you hadn\'t opened in a while could stay on an older version until updated separately.',
    'New: offline storage is much leaner — the games now share one offline cache instead of each keeping its own copy of the shared files, and every game still works fully offline.',
  ] },
  { date: '2026-07-06', title: 'Smoother arcade all around 🧈', items: [
    'Fix: Brick Breaker\'s ball (and falling power-ups) and Forcefield\'s sweeping dome now glide perfectly between physics steps — the same micro-hitch cure Meadow Flyer got, visible on any screen and especially 120 Hz.',
  ] },
  { date: '2026-07-06', title: 'New title, proper fanfare ✨', items: [
    'Fix: earning a new title lights the golden dot on the Profile button again AND replays the "★ NEW TITLE" shine on your profile card when you open it — the shine had been lost when the profile moved to the side panel.',
  ] },
  { date: '2026-07-06', title: 'Meadow Flyer: butter-smooth 🧈', items: [
    'Fix: scrolling is silky now — stems, hills, clouds and the flyer glide between physics steps instead of micro-hitching, and taps feel snappier for it. Especially visible on 120 Hz screens.',
  ] },
  { date: '2026-07-06', title: 'Frog Bonk: flashier sieges 🪄', items: [
    'New: mage frogs\' bolts streak with a sparkling arcane trail, a white-hot core and orbiting sparks, and burst on impact.',
    'New: brute stones are real spinning rocks now — shaded, speckled, with a dust burst when they hit the walls.',
    'Fix: frogs sneaking behind the castle show as faint silhouettes again instead of popping in front of the tower.',
  ] },
  { date: '2026-07-06', title: 'Keep Defender: sharper roles 🧙', items: [
    'Change: the Mage no longer slows enemies — chilling is the Frost tower\'s whole job. Arcane bolts keep their splash damage and armor piercing.',
  ] },
  { date: '2026-07-06', title: 'Bubble Pop, extra glossy 🫧', items: [
    'New: bubbles are proper candy now — grounded with soft shadows, lit through the bottom, with double sparkles and a rim of light. Colours and symbols stay exactly as readable as before.',
    'New: the board has depth — soft candy-glow pools behind the field, shaded walls and a gentle vignette.',
  ] },
  { date: '2026-07-06', title: 'Meadow Flyer got the storybook pass 🌼', items: [
    'New: the meadow is layered now — shaded clouds with sunlit caps, far hills fading into haze, a low sun by day and a moon halo at night, plus a gentle colour grade.',
    'New: the flower stems grew ribs, sunlit rims and leaf collars at the gaps, the blossoms got shading, and little grass tufts line the ground.',
    'New: every flyer has glossy eyes and soft body shading — same silhouettes, more life.',
  ] },
  { date: '2026-07-06', title: 'Keep Defender got real towers 🏰', items: [
    'New: towers are hand-drawn builds now — stone platforms that visibly grow with every upgrade (flagstone ring → brick drum → battlement crown) carrying bows, cannons, ice spires, arcane orbs and harps. The emoji still mark them in the build bar.',
    'New: enemies are drawn creatures — the rat, bat, troll, dragon, armored turtle and ant kept their species but gained shaded bodies, glossy eyes and grounded shadows.',
    'New: all six maps got the texture pass — terrain colour patches, per-map micro-texture (grass blades, snow sparkle, sand grain, lava embers), a worn road with embedded stones, a stone-built keep and a gentle colour grade.',
    'New: better battle feedback — bard-buffed towers sparkle gold with a drifting note instead of a plain circle, chilled enemies grow real ice shards with twinkling frost, and arrows kick up chips on impact.',
    'Change: the adaptive THREAT multiplier is no longer capped at 5.0× — keep dominating and the game keeps climbing (and keeps paying more score).',
    'New: map pickups got a facelift — minted gold coins with a travelling glint, a glassy haste orb and bronze event medallions, all grounded with soft shadows.',
  ] },
  { date: '2026-07-06', title: 'Meadow Flyer tidy-ups 🌼', items: [
    'Fix: fireflies now drift behind the flower stems instead of glowing on top of them.',
    'Fix: the background hills no longer vanish while still half on screen — they slide all the way out before recycling.',
  ] },
  { date: '2026-07-06', title: 'Frog Bonk got a painterly makeover 🎨🐸', items: [
    'New: the whole meadow got a texture pass — thousands of grass blades, soft colour patches and one warm light direction with real cast shadows, in all four seasons.',
    'New: the castle is built from real stones now — weathered bricks, moss, a warmly lit window and gate, and a long evening shadow.',
    'New: frogs (and the king) have glossy eyes, shaded bodies and polished helmets and gear; a gentle colour grade and vignette rounds the scene off.',
  ] },
  { date: '2026-07-06', title: 'Frog Bonk plays fair on phones 🐸📱', items: [
    'Fix: frogs no longer lurk far off screen on phones — they appear right at the screen edge, and brutes/mages never throw stones or cast spells at you from outside the view.',
    'Fix: the pea ballista\'s knockback is now a visible backward hop instead of an instant jump — no more swinging at a frog that teleported away mid-tap (and losing your combo to the whiff).',
    'Fix: knocked-back frogs can\'t be shoved off the edge of the meadow anymore.',
  ] },
  { date: '2026-07-06', title: 'New game: Frog Bonk 🐸', items: [
    'New: Frog Bonk — the frog king defends his meadow castle with a soft hammer. Tap the invading frogs (knights, mages, brutes and more) before they chomp the walls; bonked frogs boing off with a rainbow trail.',
    'Three ways to play: Waves (15 winnable waves with a between-wave upgrade shop — moat, pea ballista, stone walls), Endless (they never stop coming) and Zen (no losing, just happy bonks). Easy, Medium and Hard.',
    'Collection: five hammer skins (fluffy! inflatable! candy cane!) and four meadow seasons — sun, autumn, rain and snow.',
    'Change: Road Hop\'s tile icon is now 🚧 — the frog moved to Frog Bonk.',
    'Fix: muting the music now makes it truly silent — a faint reverb echo used to keep playing, in every game.',
  ] },
  { date: '2026-07-05', title: 'Sharper shields & a faster site ⚡', items: [
    'Fix: Forcefield now blocks every shot the shield visibly crosses — the check follows the laser\'s actual path through the dome, which used to miss most at the edges of the board.',
    'Fix: saving your display name shows a “Saved ✓” receipt and the new name appears everywhere immediately.',
    'New: the site loads noticeably faster — only YOUR language is downloaded up front (about an eighth of the old bundle); the others arrive quietly in the background so offline switching still works.',
  ] },
  { date: '2026-07-05', title: 'A tidier home & shop 🧹', items: [
    'New: home page sections can be folded — click a section name to collapse it (the ▸ arrow shows it opens back up). Your folds are remembered.',
    'New: the right-edge quick menu shows more at a glance — your name under Profile, lifetime 🏆 under Challenges, and collection progress under Collection.',
    'Change: leaner menus — the profile card left the home ☰ menu (Profile lives on the quick menu), Settings shows the update dot too, and each game\'s ☰ is now Update · Fullscreen · Language · Embed · Reset.',
    'Fix: Collection swatches now show the REAL in-game look of default items — Range\'s rings and hit-marker, the bee, the stone castle, bubble pops and Forcefield\'s golden bolt.',
    'Fix: Discord score posts stopped spamming — properly spaced out, and a zero-score run posts nothing.',
    'Fix: the » arrow on Recently played only appears when there\'s actually something to scroll.',
  ] },
  { date: '2026-07-05', title: 'Trophies, favorites & fixes 🛠️', items: [
    'Fix: weekly challenges finished inside a game now always pay their trophies — even if you only open the home page days later. Random “play today\'s pick” challenges finally show their game and progress inside games too.',
    'Fix: rearranging ★ Favorites while a search or filter was active could silently drop the hidden favorites — they stay put now.',
    'Fix: changing the language inside a game no longer restarts the game — your run keeps going and the switch applies right away. ?lang= links finally stick, too.',
    'New: buying a 🏆 100+ item in the Collection asks “spend?” first — no more losing weeks of trophies to one mis-tap.',
    'Change: Import in Settings now fully replaces this device\'s data with the backup, exactly as promised — no more leftovers mixing two profiles.',
    'Fix: coming back to the home page from a game shows your run right away — Recently played and the notification dots no longer lag behind.',
    'Fix: Forcefield — the shield is a touch more forgiving (shots that looked blocked ARE blocked), the battle station no longer hides under the score pill on sideways phones, and keys pressed with a menu open can\'t sneak a shot through anymore.',
  ] },
  { date: '2026-07-05', title: 'Home page, reworked 🏠', items: [
    'New: the games now sort into four shelves — ★ Favorites, Recently played, All games and Coming soon. Single-player and multiplayer live together under All games (multiplayer tiles keep their 👥 badge, and the Type filter still splits them).',
    'New: Recently played — full game cards of what you actually played, newest first, in a sideways-scrolling row with a » paddle. Starting a run (picking a mode and pressing Play) is what counts as played.',
    'New: rearrange your ★ Favorites by dragging — on a phone, hold a tile for a moment to lift it. A see-through copy of the card shows exactly where it will land.',
    'New: a quick menu on the right edge — Profile (wearing your current title), Challenges and Collection as big buttons. It tucks away behind a ‹‹ tab when the screen is narrow, or whenever you hide it — and it remembers your choice.',
    'New: notification dots — Profile lights up when you earn a new title, Challenges when a fresh daily or weekly challenge arrives (with a ★ NEW badge on it inside), and the ‹‹ tab carries the dot while the menu is hidden.',
    'New: Install, Language and Fullscreen buttons in the top-right corner — fullscreen helps when the installed app window has no fullscreen option of its own. Each game\'s ☰ menu got a fullscreen switch too.',
  ] },
  { date: '2026-07-05', title: 'Fixes & polish 🔧', items: [
    'Fix: updating really updates everything now — no more "Settings says up to date, but a game still shows the update dot" (a caching gremlin fed freshly-updated games stale files). The home page ☰ also lights up when an update is ready.',
    'Fix: Range — the clock ticks in real time instead of only when you shoot, finishing a Sprint shows the bar visibly filling with a golden flash before the end screen, and a record run finally shows its "★ New best!".',
    'Change: Forcefield\'s icon is now 🌐 (was 🛡️) — the globe fits defending a planet\'s atmosphere better.',
    'Fix: on phones, the Filter, Random and Compact buttons center their labels properly.',
  ] },
  { date: '2026-07-05', title: 'komyo тепер розмовляє і українською! 🇺🇦', items: [
    'New: komyo now speaks Ukrainian too! The whole site — every game, every menu and screen — is translated. Pick Українська from ⚙️ Settings on the home page, or the ☰ menu inside any game. English, Polish, Spanish, Portuguese, French and Italian are there as well, and more languages are on the way.',
  ] },
  { date: '2026-07-05', title: 'komyo teď mluví i česky! 🇨🇿', items: [
    'New: komyo now speaks Czech too! The whole site — every game, every menu and screen — is translated. Pick Čeština from ⚙️ Settings on the home page, or the ☰ menu inside any game. English, Polish, Spanish, Portuguese and French are there as well, and more languages are on the way.',
  ] },
  { date: '2026-07-05', title: 'komyo parla anche italiano! 🇮🇹', items: [
    'New: komyo now speaks Italian too! The whole site — every game, every menu and screen — is translated. Pick Italiano from ⚙️ Settings on the home page, or the ☰ menu inside any game. English, Polish, Spanish, Portuguese and French are there as well, and more languages are on the way.',
  ] },
  { date: '2026-07-05', title: 'komyo parle aussi français ! 🇫🇷', items: [
    'New: komyo now speaks French too! The whole site — every game, every menu and screen — is translated. Pick Français from ⚙️ Settings on the home page, or the ☰ menu inside any game. English, Polish, Spanish and Portuguese are there as well, and more languages are on the way.',
  ] },
  { date: '2026-07-05', title: 'komyo já fala português! 🇧🇷', items: [
    'New: komyo now speaks Portuguese too! The whole site — every game, every menu and screen — is translated. Pick Português from ⚙️ Settings on the home page, or the ☰ menu inside any game. English, Polish and Spanish are there as well, and more languages are on the way.',
  ] },
  { date: '2026-07-04', title: '¡komyo habla español! 🇪🇸', items: [
    'New: komyo now speaks Spanish too! The whole site — every game, every menu and screen — is translated. Pick Español from ⚙️ Settings on the home page, or the ☰ menu inside any game. English and Polish are there as well, and more languages are on the way.',
  ] },
  { date: '2026-07-04', title: 'New game: Forcefield 🛡️', items: [
    'New: Forcefield — a battle station charges its cannon at your planet and marks where it\'ll strike. Sweep your atmosphere dome over the mark and tap to shield the blast — deflect it, or your planet takes the hit. Play against the clock, on 3 shields, or a 1–2-player Double where the station fires both ways at a planet on each side. Easy to Hard, with unlockable planet skins and bolt colours in the Collection.',
  ] },
  { date: '2026-07-04', title: 'More polish 🧽', items: [
    'Fix: updating from the home page now truly updates every game — open any game afterwards and it\'s already on the latest version, with no per-game Update needed.',
    'Fix: on a phone, the Filter, Random and Compact buttons now sit neatly on one row instead of spilling onto another line.',
    'Fix: the Collection store held sideways (landscape) no longer leaves a gap under the title or clips the "See titles" button off the bottom.',
  ] },
  { date: '2026-07-04', title: 'Play in your language 🌍', items: [
    'New: komyo now speaks Polish! The whole site — every game, every menu and screen — is translated. Pick your language from ⚙️ Settings on the home page, or the ☰ menu inside any game. English stays the default, and more languages are on the way.',
  ] },
  { date: '2026-07-04', title: 'CRT mode 🖥️', items: [
    'New: unlock CRT display mode in the 🎨 Collection — a retro phosphor glow over the whole site (games, menus, everything). Turn it on from the store or the ☰ menu and pick a colour: green, amber, cyan or mono. Hover a colour to preview it live before you choose.',
    'Change: the CHALLENGE tile badge is now gold to match your trophies; the NEW badge is green.',
    'New: a Terminal cursor skin in the 🎨 Collection — a blinking block cursor like an old terminal prompt; it glows in your CRT colour when CRT mode is on.',
  ] },
  { date: '2026-07-04', title: 'Fixes big and small 🛠️', items: [
    'Fix: in Brick Breaker\'s Endless mode, the falling bricks can now actually get you — if a row reaches your paddle line the run ends, instead of bricks sliding harmlessly off the bottom.',
    'Fix: the Asteroids+ upgrade picker no longer shows its heading twice.',
    'New: updates are fully in your hands — a new version never reloads the page on its own; it just lights the ☰ menu dot until you press Update. Updating from the homepage now refreshes every game too, not only the ones you\'ve opened.',
    'Fix: the trophies & Collection pills inside a game\'s 🏆 panel now match the ones on the homepage.',
    'Fix: the Collection store now lays out properly on a phone held sideways — the items get the room instead of the search and progress bars.',
    'Fix: game badges (NEW, POPULAR…) no longer overlap the icon in the compact tile view — they show as small shiny dots there.',
    'New: you can link straight to the Collection store or the Titles ladder (komyo.online/?m=cosmetics · ?m=titles).',
    'Fix: Meadow Flyer\'s menu spacing — a little more room between the Day/Night buttons and the text below.',
  ] },
  { date: '2026-07-03', title: 'The Cosmetics shop is open 🎨', items: [
    'New: spend your challenge trophies in the 🎨 Cosmetics store — skins for every game. Open it from the 🏆 Challenges panel (the gold COSMETICS pill) or your profile. Your points are now called trophies: your lifetime total still climbs the titles ladder, and your spendable balance buys cosmetics. Spending never slows your title.',
    'New: pick your skin right in each game\'s menu — buy a locked one on the spot with trophies. Neon Snake food (Cherry, Golden Apple, Gem, Star Fruit, Rainbow Orb), Brick Breaker paddles & balls (Wood, Neon Ice, Lava, Chrome · 8-Ball, Comet, Disco, Plasma), Keep Defender castles (Oak, Sandcastle, Ice, Obsidian), Bubble Pop pop-effects & shooters, Range targets & hit markers, Stack block palettes, Asteroids ship colours (plus a whole-game CRT Green retro mode), and Asteroids+ hulls & engine trails.',
    'New: Meadow Flyer\'s birds joined the cosmetics — buy any bird in any order with trophies. Your old banked coins converted straight into trophies (1:1) and every bird you\'d already unlocked stays yours.',
    'New: desktop cursor skins for the whole site — Crosshair, Paw, Pixel Sword, Neon Comet and a Rainbow Trail (the last two leave a little wake as you move).',
    'New: good runs now pay a bonus — your first 3 good runs each day give +5 trophies each. The end-of-run screen shows the bonus as you earn it.',
    'New: your profile shows how much of the collection you\'ve unlocked, and the Challenges panel shows your collection bar + today\'s good-run bonus.',
  ] },
  { date: '2026-07-03', title: 'Offline everywhere & title reveals ✨', items: [
    'New: visit the homepage once and EVERY game saves itself for offline — play the whole catalogue on a plane or with no signal, even games you\'ve never opened.',
    'Fix: the "Update now" buttons (Settings and the in-game ☰ menu) no longer hang on "Updating…" — updating now finishes with a quick automatic reload.',
    'New: earning a new title lights a little gold dot on the ☰ menu — open it and your new title is revealed with a shine.',
    'New: in Neon Snake on a phone held sideways, the board handle now slides the arena left–right (up–down stays for portrait).',
    'Fix: the in-game 🏆 button only glows while that game\'s challenge is still unfinished — completing it turns the glow off.',
    'Fix: Bubble Pop\'s shooter glow now matches the color of the bubble you\'re about to shoot (it was always green and lied to you).',
    'Fix: Keep Defender sideways on a phone — the map no longer starts tucked under the score bar.',
    'Fix: Asteroids+ score/health bar is a slim strip on phones now, in both orientations, instead of covering the top of the action.',
    'Fix: Brick Breaker\'s ◀ ▶ touch hints show up reliably on touch screens (some devices never got them).',
    'Fix: the Menu and Komyo buttons in games no longer start a "drag" instead of a click.',
    'Improved: the ☰ version label fits on one line again, and the profile\'s little (i) is gone — tap your points in the Challenges panel to browse the titles ladder.',
    'New: game menus on a phone held sideways got a full rework — modes and unlock grids (like Meadow Flyer\'s birds) fill the left side, while the game name, options and the Play button stack in a right rail. No more scrolling to find a mode.',
    'New: Keep Defender\'s ⏸ now opens the same pause menu as every other game (resume / quit to menu), instead of a bare overlay.',
    'Improved: the "Leave this run?" and reset boxes now match the look of the game you\'re in, and the destructive button glows red when selected, not blue.',
    'Teaser: Neon Snake\'s menu shows a locked "Enhanced" mode (wild power-up drops), and Range teases a locked "Reaction" mode (average reaction-time test) — both coming.',
    'Fix: dismissing the "tap to play" splash no longer clicks whatever sat underneath it (no more accidentally starting a game or switching modes with that first tap).',
    'New: 2048 joined the coming-soon shelf — the classic slide-and-merge puzzle.',
    'New: Asteroids+ upgrades got little laser icons in the level-up picker and the Drydock — scan your build at a glance, no reading needed.',
    'New: the Drydock shows every upgrade on one screen now (no more scrolling to find Continue), in both orientations.',
    'New: on touch screens, shop and level-up cards use tap-to-select, tap-again-to-buy — read what an upgrade does before committing, and no more accidental picks. A big BUY/TAKE button appears for the selected card.',
    'Fix: open menus and panels no longer let the page behind them scroll.',
    'Fix: genre tags on the game tiles are easier to read (better contrast), and the homepage no longer shifts while tiles load on phones.',
    'New: challenge points got 10× bigger — dailies now pay 10, weeklies 50, and every title threshold scaled with them. Your saved points were multiplied too, so nobody lost a thing.',
    'New: daily challenges are properly shuffled now — a different surprise each day (same one for everyone), instead of marching through an easy week then a brutal week.',
    'New: challenge targets retuned across every game after a review — Asteroids+ goals dropped from a marathon 50k/150k to 15k/30k, Keep Defender asks for wave 5 or wave 10 (no more duplicate goal), Asteroids gained a harder 8k tier, and Snake/Bubble Pop/Stack/Meadow Flyer targets adjusted. A "good run" now means clearing the harder daily bar.',
    'Fix: Keep Defender\'s score bar sits on its own row in portrait at every screen size (it could slide under the top buttons on tablets), and it\'s a slim strip on phones now.',
    'Improved: on a phone held sideways the homepage header is compact, so the games are visible right away.',
  ] },
  { date: '2026-07-02', title: 'Titles & better sharing 👑', items: [
    'New: Meadow Flyer\'s flyers are real characters now, and there are nine — bee, robin, bluebird, parrot, plus new raven, owl, Bielik (the white-tailed eagle) and Raróg (the fiery falcon of Slavic legend), topped by a phoenix made of fire with a glowing ember trail. Menu icons show the actual birds (no more yellow icon on a blue bird), and unlocks are a real ladder up to 1,000 banked points.',
    'New: every game has a ☰ menu (top right) showing your game version and an Update button — greyed "Up to date" when you\'re current, lit up when a new version is ready (a little dot on ☰ too). Updates never interrupt your play anymore. Embed and Reset scores moved in there as well.',
    'New: Settings now shows the site version with an "Update now" button that refreshes the site and every game at once — and version labels everywhere show when the build was deployed.',
    'New: earn a title with challenge points — from Goblin of the Gutter to Emperor of Eternity. Your profile shows it off with an ever-shinier glow (and sparkles at the higher ranks).',
    'New: tap the little (i) next to your title to see the whole ladder — every rank, its shine, and the points it takes.',
    'New: in the Challenges panel, tap your points total to see what points are for — the titles ladder opens right there (more rewards planned).',
    'Improved: the profile page got a cleaner look — your title, name, challenge points, good runs and play stats all up top.',
    'New: score cards got a full redesign — every game shares a flashy card in its own colors, with a glowing frame, sparkles and your name. Speedruns show your time.',
    'New: the Discord games-log now posts the score card itself, with the play link right under it.',
    'New: sharing a score card or your profile now opens a small menu — send it straight to an app, copy the image, or download it.',
    'Fix: the shared profile image is now cropped to its content (no more half-empty picture) and includes the title sparkles.',
    'Fix: copying a shared image no longer pastes twice in Discord and other chats.',
    'Improved: games render razor-sharp on phones and other high-density screens (they were slightly blurry before).',
    'New: every game now shows which mode you\'re playing right in the score bar (map, difficulty, mode).',
    'New: resetting your saved data now asks you to press and hold the button for 3 seconds — no more accidental wipes.',
    'Fix: Bubble Pop\'s Zen mode no longer dead-ends — clearing the board celebrates and brings in a fresh one.',
    'Fix: Keep Defender on a phone held sideways — the tower list scrolls now, so Archer isn\'t stuck off-screen.',
    'Fix: in Neon Snake, sliding the board all the way up/down can no longer tuck it under the score bar or push the bottom wall off-screen.',
    'Fix: in Range, rotating your phone mid-run pulls the current target back on-screen.',
    'Fix: in Neon Snake, quick double-turns now land exactly as pressed (inputs are buffered, none get lost).',
    'Fix: Meadow Flyer on wide screens no longer starts with a long empty flight — the first trees are a fair distance away, like on phones.',
    'Fix: score cards are sharper — the shared image now keeps its full resolution, so it no longer looks pixelated when zoomed or posted to Discord on mobile.',
    'Fix: in Asteroids+, “Reset scores” now resets Asteroids+ — it was clearing Classic Asteroids’ bests instead (sorry!) and leaving its own untouched.',
    'Fix: the 🏆 challenges button inside Asteroids+ now actually shows the daily & weekly goals (it opened an empty panel before).',
    'Fix: the “★ New best!” banner in Meadow Flyer and Stack now appears when you beat your record — it never showed before.',
    'Fix: Brick Breaker’s level-up and lost-ball sounds and Bubble Pop’s game-over sound are back (they had gone silent).',
    'Fix: speedrun clocks in both Asteroids no longer keep ticking while the game is paused or in a menu — and finishing a speedrun on the exact frame you crash now counts as the win it is.',
    'Fix: Keep Defender’s speed button now reads 1x/2x honestly (there is no 3x), and the Marsh map no longer secretly weakens your archers — it plays exactly as its description says.',
    'Fix: “Reset all data” on the home page keeps your chosen player name.',
    'Fix: the “Have 3 good runs today” and “10 good runs this week” challenges now actually track your good runs and award their points — they could never complete before. Challenge progress also can’t double-count a run anymore.',
    'Improved: Keep Defender score now rewards difficulty — points count ×1.5 on Medium and ×2 on Hard, so a hard run isn’t out-scored by a cruisy easy one (gold rewards are unchanged).',
    'Fix: Keep Defender bosses were nearly unkillable on Hard — they now have half the health on Hard and 30% less on Medium (Easy bosses are unchanged), lumber 20% slower, and no longer get the hidden speed boost from the threat meter (regular enemies still do).',
    'Improved: Keep Defender stays readable and audible late-game — with a board full of towers, spell/blast effects thin out past a visual budget and rapid-fire sounds are rate-limited instead of stacking into noise.',
    'Improved: Discord score posts now follow your privacy choices — nothing is sent unless you accept the cookie banner, posts are anonymous by default, and a new ⚙️ Settings toggle shows your nickname only if you want the glory. Posts are also limited to about one per minute.',
    'Fix: on high-refresh screens (90/120/144 Hz phones and monitors) five games ran up to twice too fast — Meadow Flyer, Stack, Range, Bubble Pop and Keep Defender now play at the intended speed on every screen. Range’s recorded reaction and sprint times are accurate there too, and Stack’s Time Attack lasts its full 60 seconds.',
  ] },
  { date: '2026-07-01', title: 'Roll the dice 🎲', items: [
    'New: a 🎲 Random button on the home page picks a game for you — it leans toward ones you haven’t tried yet, an easy way to discover something new.',
    'New: a random-pick daily & weekly challenge — “play today’s pick” — nudging you toward games you might have missed.',
    'Fix: in Bubble Pop, bubbles now stick properly to the top row instead of occasionally vanishing or snapping to the wrong spot.',
  ] },
  { date: '2026-07-01', title: 'Your player profile 👤', items: [
    'New: a My profile page (menu → 👤 My profile) — see your totals, favorite game and genre, good runs, and your best score in every mode of every game, laid out as tiles and ranked by how much you play them. Share the whole thing as an image.',
    'Everything stays on your device (nothing to sign up for), and carries over with Export / import.',
  ] },
  { date: '2026-07-01', title: 'Sound on 🔊', items: [
    'New: every game now has music — a themed backdrop track that plays on the menu and keeps going while you play. Keep Defender even changes its tune per map (grassland, ice, lava, desert, dungeon, marsh).',
    'Improved: punchier sound effects across every game — richer hits, pops, explosions and pickups, with a touch of space. Asteroids fire now sounds like a proper laser.',
    'New: little win / lose / level-up fanfares on the end screens.',
    'New: a Settings page (menu → ⚙️ Settings) to turn sound effects and music on or off — or set their volume — for the whole site at once. Each game still has its own sound menu too.',
  ] },
  { date: '2026-07-01', title: 'Asteroids+ joins the new menu', items: [
    'New: Asteroids+ now opens with the same one-screen card menu as every other game — pick Level-up, Milestones or Wave Shop (plus Speedrun) in a single screen, over a drifting field of asteroids and enemy ships. Its level-up picker and between-wave shop got the matching look too.',
    'New: Asteroids+ asks before you leave a run from the menu, so you don’t lose a run by accident.',
  ] },
  { date: '2026-07-01', title: 'A fresh menu for every game', items: [
    'New: every game now opens with a redesigned menu — pick your mode and options from cards, sliders and toggles, over a gentle animated backdrop of the game itself (drifting asteroids, a wandering snake, meadow leaves by day and fireflies by night, your Keep Defender map, and more). Play, pause, 🎮 Controls and 🏆 Challenges work the same in every game.',
    'New: Range — choose Timed (10 / 30 / 60s) or a Sprint target (10 / 50 / 100 targets), with a moving-targets toggle.',
    'New: Keep Defender — pick your map from a preview picker and set the difficulty on a slider.',
    'New: Meadow Flyer — choose Day or Night and your flyer from a grid; sunny days now have leaves drifting on the wind.',
    'New: Neon Snake, Brick Breaker & Stack — the same card/slider menus, with your picks saved in the link so you can share the exact setup.',
    'New: you now start with a playful random nickname (like “Sneaky Otter”) instead of “anonymous” — change it anytime in the menu (✏️).',
    'New: a Terms of Service page — find it in the menu under License & privacy.',
    'Fix: the changelog search now narrows to the lines that match your words and highlights them.',
  ] },
  { date: '2026-07-01', title: 'Challenges in your games', items: [
    'New: Asteroids & Bubble Pop — a 🏆 Challenges button right in the game shows today’s daily and weekly goals (and gently glows when the game you’re in is the one with a challenge), so you can check the goal without going back to the menu.',
    'New: a back-to-top button on the home page — appears once you’ve scrolled the games list down.',
    'Improved: no more name pop-up when you arrive — you start as anonymous, and set a display name only if you want to (menu → ✏️). One less thing between you and the games.',
    'Changed: Bubble Pop — Speedrun is now a “Time-based descent” toggle you can switch on for Arcade or Endless (leave it off and the grid moves as you shoot instead of on a clock). Zen never descends.',
  ] },
  { date: '2026-06-30', title: 'Walls, taps & rotation', items: [
    'New: Asteroids & Bubble Pop — a 🎮 Controls button (top-right) shows how to play (keyboard, mouse, touch) any time, even mid-game; and the Play button is now bigger and always reachable.',
    'New: a CHALLENGE badge on game tiles — when a game is the focus of today’s daily or this week’s weekly challenge, its tile is marked so you can spot it at a glance, with a matching CHALLENGE filter to show just those games.',
    'Improved: search now matches a game’s labels too — type “challenge”, “popular”, “new” or “updated” to see just those games.',
    'New: Bubble Pop — a redesigned start menu. Pick your mode from cards (Arcade / Speedrun / Endless / Zen) that show what each one plays like, with a little icon and your best score; the whole menu is keyboard-friendly, pause works the same from Esc or the ⏸ button, and hitting Menu mid-game asks before it drops your run.',
    'New: Asteroids — a redesigned start menu. Pick your mode from cards (Classic / Classic+) that show what each one plays like and your best score, flip on Speedrun with a tick, and steer the whole menu with the keyboard. Hitting Menu mid-run now asks before it drops your run, and your picks live in the link so you can share the exact setup.',
    'Fix: Asteroids & Asteroids+ — in Speedrun mode your shared/Discord result now leads with your clear time (the actual goal), instead of your score and wave.',
    'Improved: offline play — open komyo once online and every game is saved to play offline (even ones you haven’t opened yet), and refreshing with no connection no longer breaks the app. Try it in airplane mode!',
    'New: Bubble Pop — the play area now has real walls and a ceiling, in both portrait and landscape. Shots bounce off the side walls and stick to the top, and on wide screens the bubbles sit in a centered column.',
    'Fix: Bubble Pop — on phones, tapping a new spot now shoots there. Before, a fresh tap could still fire at wherever you last aimed.',
    'New: Neon Snake — on phones, drag the ↕ handle in the board’s corner to slide the playfield up or down to a comfier spot. It’s remembered next time.',
    'Fix: installed games now respect your phone’s rotation lock — if you’ve turned auto-rotate off, the app stays put instead of spinning. (Reinstall the game to pick this up.)',
  ] },
  { date: '2026-06-29', title: 'Polish & fixes', items: [
    'New: Asteroids+ — a big rebalance. It’s now a finite run that ends with a two-boss finale on wave 30 (beat it for a Victory), upgrades are gentler and now lapse after a few waves so you keep choosing, and a new red kamikaze enemy (from wave 6) charges in and explodes — don’t pop it in your face.',
    'New: Asteroids+ — light aim assist: shots that just graze an enemy curve in and connect.',
    'Improved: Asteroids+ — your ship is now a bright white so it never gets lost among the asteroids, bosses can return fire as far as you can shoot, and pickups are tuned so a good run is rewarded without burying you in power-ups.',
    'New: Meadow Flyer — long runs no longer level off. Past a score of 55 the world speeds up, peaking around 100, so a great run stays a real challenge.',
    'Fix: on narrow phones the top bar no longer crowds itself — the Menu button and the sound/pause buttons keep clear of each other.',
    'Fix: the ‹ Menu button now only shows while you’re actually playing, not on a game’s own menu (where it was easy to mistake for “back to the website”).',
    'Fix: Range — on phones the shot marker now stays exactly where you fired, instead of drifting along with your finger.',
    'Fix: Bubble Pop — the grid now keeps its shape when a new row drops in (no more sideways jump), and your shot sticks to the spot you aimed at instead of occasionally slipping behind the pack.',
    'Improved: Bubble Pop — bubbles render crisp and sharp on high-resolution screens.',
    'Improved: the Filter panel’s Highlights and Genres are now tappable chips (matching the Type buttons) instead of checkboxes — and the panel can be resized.',
    'New: you can now embed the whole arcade on your site, not just a single game (menu → “Embed a game”).',
    'New: direct links to the menu pages — e.g. komyo.online/?m=faq or ?m=changelog open straight to that panel.',
    'New: a quick “?” tip in the search box — search by game name or genre (arcade, puzzle, kids…).',
    'Improved: score posts in our Discord now show a tidy “▶ Play this game on Komyo” link instead of a long raw address.',
    'Fix: completed challenges now reliably show up in your History — even if you finished one inside a game and didn’t reopen the home page that day.',
    'New: Keep Defender — pick a difficulty (Easy / Medium / Hard) on the start screen. Tougher levels make enemies tankier (health now compounds each wave) and tighten your gold, so it stays a real fight.',
    'New: Keep Defender — set each tower’s targeting priority (First / Last / Strongest / Weakest / Closest) from its panel.',
    'Improved: Keep Defender — your shared/Discord result now shows your Score as well as waves survived (so a tougher difficulty actually reads as the bigger run it is).',
  ] },
  { date: '2026-06-28', title: 'Challenges, score cards & more', items: [
    'New: game tiles now show up to three genre tags, each in its own consistent color, and you can filter by any of them.',
    'New: a stack of fresh games is on the way — peek the "coming soon" tiles for what we’re building next.',
    'Fix: Keep Defender — the castle and path no longer clip off the screen edge, and the board clears the score bar.',
    'Fix: Bubble Pop — in landscape on phones the starting bubbles no longer crowd the launcher.',
    'Fix: Asteroids+ — the boss no longer overlaps the score bar on phone screens.',
    'New: Asteroids+ — the roguelite Asteroids (XP, upgrades, bosses, a wave shop) is now its own game. Plain Asteroids is the classic arcade one. Pick your mode right inside each game.',
    'New: Daily & Weekly Challenges — tap 🏆 for today’s challenge plus a bigger weekly one. Earn points (1 per daily, 5 per weekly) that only ever go up, with a History list of everything you’ve completed (up to a year, "Load more" to go back).',
    'New: Score cards — share a picture of your score from the end screen (📷), straight to your apps.',
    'New: Embed games on your own site or blog — an Embed button in each game’s sound menu, plus "Embed a game" in the main menu.',
    'New: a ⏸ pause button in every game (top-right, next to sound).',
    'New: Export / import your data — back it up or move it between devices, no account needed (in the menu under "Your data").',
    'New: a Compact tile view (button by the filters) so more games fit on screen, plus an FAQ and a Privacy policy in the menu.',
    'New: Neon Snake has on-screen arrow buttons on phones — tap to turn instead of swiping; drag the pad anywhere, or tuck it away (and bring it back) with the ✕ / 🎮 button.',
    'New: Brick Breaker on phones — hold the left or right side of the screen to slide the paddle (instead of dragging).',
    'New: Bubble Pop modes — Arcade and Endless now build pressure as you shoot rather than on a clock, with a new Speedrun mode that keeps the timer. Your loaded bubble also auto-swaps if its color is no longer on the board.',
    'Fix: games now re-fit correctly when you rotate your phone between portrait and landscape — Stack stays centered, Brick Breaker keeps room to react, Bubble Pop sticks to portrait on phones, Tower Defense’s menu and keep fit the screen, Asteroids’ end screen fits in landscape.',
    'Fix: Brick Breaker — the paddle now moves instantly and stops the moment you let go; in portrait the top bricks no longer hide under the score bar.',
    'Fix: Brick Breaker — the paddle waits centered until you launch, and the on-screen ◀ ▶ move hints now show in portrait too (not just landscape).',
    'Fix: Asteroids & Asteroids+ — a mode is preselected so Play works right away, and picking a mode now works on phones.',
    'Fix: the Filter panel now fits the screen on phones in landscape — it no longer runs off the edge, and the genre list scrolls.',
    'Fix: Range’s "race to 100" progress bar now tracks targets hit, not points.',
    'Fix: Keep Defender — the upgrade button is greyed out until you can afford it, then pops in.',
  ] },
  { date: '2026-06-27', title: 'We are now Komyo Games', items: [
    'New name & logo: funyo is now Komyo Games — same games, fresh fox mascot.',
    'New: your score auto-posts to our Discord on game-over — now with the game mode + stats (accuracy, level, wave…). Set a display name in the menu, or stay anonymous.',
  ] },
  { date: '2026-06-27', title: 'Home redesign & polish', items: [
    'New: redesigned home page — slide-out menu, instant search and genre filters (your filters now save in the link, so you can bookmark them).',
    'New: NEW and UPDATED badges on game tiles, so fresh and recently-improved games are easy to spot.',
    'New: “Reset all data” to clear your scores, progress and favorites across every game.',
    'New: this changelog 🙂',
    'Fix: Brick Breaker ran too fast on some phones — speed is now consistent everywhere.',
    'Fix: Range “Sprint” is now a proper race to 100 targets.',
  ] },
  { date: '2026-06-26', title: 'First games launch', items: [
    'Added 8 games: Asteroids, Keep Defender, Bubble Pop, Brick Breaker, Stack, Meadow Flyer, Range and Neon Snake.',
  ] },
];
