// Player-facing changelog — newest first. Single source of truth for BOTH the in-page
// 🗒️ Changelog modal (index.html) AND the Discord changelog post: the GitHub Action posts
// only the entries ADDED in a push (diff vs the previous commit), so Discord == this file.
// One release per date: { date:'YYYY-MM-DD', title:'…', items:['New: …','Fix: …'] }.
// Keep bullets plain-language and about what a PLAYER notices — never kit/test/build/refactor.
window.CHANGELOG = [
  { date: '2026-07-03', title: 'Offline everywhere & title reveals ✨', items: [
    'New: visit the homepage once and EVERY game saves itself for offline — play the whole catalogue on a plane or with no signal, even games you\'ve never opened.',
    'Fix: the "Update now" buttons (Settings and the in-game ☰ menu) no longer hang on "Updating…" — updating now finishes with a quick automatic reload.',
    'New: earning a new title lights a little gold dot on the ☰ menu — open it and your new title is revealed with a shine.',
    'New: in Neon Snake on a phone held sideways, the board handle now slides the arena left–right (up–down stays for portrait).',
    'Fix: the in-game 🏆 button only glows while that game\'s challenge is still unfinished — completing it turns the glow off.',
    'Fix: Bubble Pop\'s shooter glow now matches the color of the bubble you\'re about to shoot (it was always green and lied to you).',
    'Fix: Keep Defender sideways on a phone — the map no longer starts tucked under the score bar.',
    'Fix: Asteroids+ score/health bar is a slim strip on phones now, in both orientations, instead of covering the top of the action.',
    'Fix: Brick Breaker\'s ◀ ▶ touch hints show up reliably on touch screens (some devices never got them).',
    'Fix: the Menu and Komyo buttons in games no longer start a "drag" instead of a click.',
    'Improved: the ☰ version label fits on one line again, and the profile\'s little (i) is gone — tap your points in the Challenges panel to browse the titles ladder.',
    'New: game menus on a phone held sideways got a full rework — modes and unlock grids (like Meadow Flyer\'s birds) fill the left side, while the game name, options and the Play button stack in a right rail. No more scrolling to find a mode.',
    'New: Keep Defender\'s ⏸ now opens the same pause menu as every other game (resume / quit to menu), instead of a bare overlay.',
    'Improved: the "Leave this run?" and reset boxes now match the look of the game you\'re in, and the destructive button glows red when selected, not blue.',
    'Teaser: Neon Snake\'s menu shows a locked "Enhanced" mode (wild power-up drops), and Range teases a locked "Reaction" mode (average reaction-time test) — both coming.',
    'Fix: dismissing the "tap to play" splash no longer clicks whatever sat underneath it (no more accidentally starting a game or switching modes with that first tap).',
    'New: 2048 joined the coming-soon shelf — the classic slide-and-merge puzzle.',
    'New: Asteroids+ upgrades got little laser icons in the level-up picker and the Drydock — scan your build at a glance, no reading needed.',
    'New: the Drydock shows every upgrade on one screen now (no more scrolling to find Continue), in both orientations.',
    'New: on touch screens, shop and level-up cards use tap-to-select, tap-again-to-buy — read what an upgrade does before committing, and no more accidental picks. A big BUY/TAKE button appears for the selected card.',
    'Fix: open menus and panels no longer let the page behind them scroll.',
    'Fix: genre tags on the game tiles are easier to read (better contrast), and the homepage no longer shifts while tiles load on phones.',
    'New: challenge points got 10× bigger — dailies now pay 10, weeklies 50, and every title threshold scaled with them. Your saved points were multiplied too, so nobody lost a thing.',
    'New: daily challenges are properly shuffled now — a different surprise each day (same one for everyone), instead of marching through an easy week then a brutal week.',
    'New: challenge targets retuned across every game after a review — Asteroids+ goals dropped from a marathon 50k/150k to 15k/30k, Keep Defender asks for wave 5 or wave 10 (no more duplicate goal), Asteroids gained a harder 8k tier, and Snake/Bubble Pop/Stack/Meadow Flyer targets adjusted. A "good run" now means clearing the harder daily bar.',
    'Fix: Keep Defender\'s score bar sits on its own row in portrait at every screen size (it could slide under the top buttons on tablets), and it\'s a slim strip on phones now.',
    'Improved: on a phone held sideways the homepage header is compact, so the games are visible right away.',
  ] },
  { date: '2026-07-02', title: 'Titles & better sharing 👑', items: [
    'New: Meadow Flyer\'s flyers are real characters now, and there are nine — bee, robin, bluebird, parrot, plus new raven, owl, Bielik (the white-tailed eagle) and Raróg (the fiery falcon of Slavic legend), topped by a phoenix made of fire with a glowing ember trail. Menu icons show the actual birds (no more yellow icon on a blue bird), and unlocks are a real ladder up to 1,000 banked points.',
    'New: every game has a ☰ menu (top right) showing your game version and an Update button — greyed "Up to date" when you\'re current, lit up when a new version is ready (a little dot on ☰ too). Updates never interrupt your play anymore. Embed and Reset scores moved in there as well.',
    'New: Settings now shows the site version with an "Update now" button that refreshes the site and every game at once — and version labels everywhere show when the build was deployed.',
    'New: earn a title with challenge points — from Goblin of the Gutter to Emperor of Eternity. Your profile shows it off with an ever-shinier glow (and sparkles at the higher ranks).',
    'New: tap the little (i) next to your title to see the whole ladder — every rank, its shine, and the points it takes.',
    'New: in the Challenges panel, tap your points total to see what points are for — the titles ladder opens right there (more rewards planned).',
    'Improved: the profile page got a cleaner look — your title, name, challenge points, good runs and play stats all up top.',
    'New: score cards got a full redesign — every game shares a flashy card in its own colors, with a glowing frame, sparkles and your name. Speedruns show your time.',
    'New: the Discord games-log now posts the score card itself, with the play link right under it.',
    'New: sharing a score card or your profile now opens a small menu — send it straight to an app, copy the image, or download it.',
    'Fix: the shared profile image is now cropped to its content (no more half-empty picture) and includes the title sparkles.',
    'Fix: copying a shared image no longer pastes twice in Discord and other chats.',
    'Improved: games render razor-sharp on phones and other high-density screens (they were slightly blurry before).',
    'New: every game now shows which mode you\'re playing right in the score bar (map, difficulty, mode).',
    'New: resetting your saved data now asks you to press and hold the button for 3 seconds — no more accidental wipes.',
    'Fix: Bubble Pop\'s Zen mode no longer dead-ends — clearing the board celebrates and brings in a fresh one.',
    'Fix: Keep Defender on a phone held sideways — the tower list scrolls now, so Archer isn\'t stuck off-screen.',
    'Fix: in Neon Snake, sliding the board all the way up/down can no longer tuck it under the score bar or push the bottom wall off-screen.',
    'Fix: in Range, rotating your phone mid-run pulls the current target back on-screen.',
    'Fix: in Neon Snake, quick double-turns now land exactly as pressed (inputs are buffered, none get lost).',
    'Fix: Meadow Flyer on wide screens no longer starts with a long empty flight — the first trees are a fair distance away, like on phones.',
    'Fix: score cards are sharper — the shared image now keeps its full resolution, so it no longer looks pixelated when zoomed or posted to Discord on mobile.',
    'Fix: in Asteroids+, “Reset scores” now resets Asteroids+ — it was clearing Classic Asteroids’ bests instead (sorry!) and leaving its own untouched.',
    'Fix: the 🏆 challenges button inside Asteroids+ now actually shows the daily & weekly goals (it opened an empty panel before).',
    'Fix: the “★ New best!” banner in Meadow Flyer and Stack now appears when you beat your record — it never showed before.',
    'Fix: Brick Breaker’s level-up and lost-ball sounds and Bubble Pop’s game-over sound are back (they had gone silent).',
    'Fix: speedrun clocks in both Asteroids no longer keep ticking while the game is paused or in a menu — and finishing a speedrun on the exact frame you crash now counts as the win it is.',
    'Fix: Keep Defender’s speed button now reads 1x/2x honestly (there is no 3x), and the Marsh map no longer secretly weakens your archers — it plays exactly as its description says.',
    'Fix: “Reset all data” on the home page keeps your chosen player name.',
    'Fix: the “Have 3 good runs today” and “10 good runs this week” challenges now actually track your good runs and award their points — they could never complete before. Challenge progress also can’t double-count a run anymore.',
    'Improved: Keep Defender score now rewards difficulty — points count ×1.5 on Medium and ×2 on Hard, so a hard run isn’t out-scored by a cruisy easy one (gold rewards are unchanged).',
    'Fix: Keep Defender bosses were nearly unkillable on Hard — they now have half the health on Hard and 30% less on Medium (Easy bosses are unchanged), lumber 20% slower, and no longer get the hidden speed boost from the threat meter (regular enemies still do).',
    'Improved: Keep Defender stays readable and audible late-game — with a board full of towers, spell/blast effects thin out past a visual budget and rapid-fire sounds are rate-limited instead of stacking into noise.',
    'Improved: Discord score posts now follow your privacy choices — nothing is sent unless you accept the cookie banner, posts are anonymous by default, and a new ⚙️ Settings toggle shows your nickname only if you want the glory. Posts are also limited to about one per minute.',
    'Fix: on high-refresh screens (90/120/144 Hz phones and monitors) five games ran up to twice too fast — Meadow Flyer, Stack, Range, Bubble Pop and Keep Defender now play at the intended speed on every screen. Range’s recorded reaction and sprint times are accurate there too, and Stack’s Time Attack lasts its full 60 seconds.',
  ] },
  { date: '2026-07-01', title: 'Roll the dice 🎲', items: [
    'New: a 🎲 Random button on the home page picks a game for you — it leans toward ones you haven’t tried yet, an easy way to discover something new.',
    'New: a random-pick daily & weekly challenge — “play today’s pick” — nudging you toward games you might have missed.',
    'Fix: in Bubble Pop, bubbles now stick properly to the top row instead of occasionally vanishing or snapping to the wrong spot.',
  ] },
  { date: '2026-07-01', title: 'Your player profile 👤', items: [
    'New: a My profile page (menu → 👤 My profile) — see your totals, favorite game and genre, good runs, and your best score in every mode of every game, laid out as tiles and ranked by how much you play them. Share the whole thing as an image.',
    'Everything stays on your device (nothing to sign up for), and carries over with Export / import.',
  ] },
  { date: '2026-07-01', title: 'Sound on 🔊', items: [
    'New: every game now has music — a themed backdrop track that plays on the menu and keeps going while you play. Keep Defender even changes its tune per map (grassland, ice, lava, desert, dungeon, marsh).',
    'Improved: punchier sound effects across every game — richer hits, pops, explosions and pickups, with a touch of space. Asteroids fire now sounds like a proper laser.',
    'New: little win / lose / level-up fanfares on the end screens.',
    'New: a Settings page (menu → ⚙️ Settings) to turn sound effects and music on or off — or set their volume — for the whole site at once. Each game still has its own sound menu too.',
  ] },
  { date: '2026-07-01', title: 'Asteroids+ joins the new menu', items: [
    'New: Asteroids+ now opens with the same one-screen card menu as every other game — pick Level-up, Milestones or Wave Shop (plus Speedrun) in a single screen, over a drifting field of asteroids and enemy ships. Its level-up picker and between-wave shop got the matching look too.',
    'New: Asteroids+ asks before you leave a run from the menu, so you don’t lose a run by accident.',
  ] },
  { date: '2026-07-01', title: 'A fresh menu for every game', items: [
    'New: every game now opens with a redesigned menu — pick your mode and options from cards, sliders and toggles, over a gentle animated backdrop of the game itself (drifting asteroids, a wandering snake, meadow leaves by day and fireflies by night, your Keep Defender map, and more). Play, pause, 🎮 Controls and 🏆 Challenges work the same in every game.',
    'New: Range — choose Timed (10 / 30 / 60s) or a Sprint target (10 / 50 / 100 targets), with a moving-targets toggle.',
    'New: Keep Defender — pick your map from a preview picker and set the difficulty on a slider.',
    'New: Meadow Flyer — choose Day or Night and your flyer from a grid; sunny days now have leaves drifting on the wind.',
    'New: Neon Snake, Brick Breaker & Stack — the same card/slider menus, with your picks saved in the link so you can share the exact setup.',
    'New: you now start with a playful random nickname (like “Sneaky Otter”) instead of “anonymous” — change it anytime in the menu (✏️).',
    'New: a Terms of Service page — find it in the menu under License & privacy.',
    'Fix: the changelog search now narrows to the lines that match your words and highlights them.',
  ] },
  { date: '2026-07-01', title: 'Challenges in your games', items: [
    'New: Asteroids & Bubble Pop — a 🏆 Challenges button right in the game shows today’s daily and weekly goals (and gently glows when the game you’re in is the one with a challenge), so you can check the goal without going back to the menu.',
    'New: a back-to-top button on the home page — appears once you’ve scrolled the games list down.',
    'Improved: no more name pop-up when you arrive — you start as anonymous, and set a display name only if you want to (menu → ✏️). One less thing between you and the games.',
    'Changed: Bubble Pop — Speedrun is now a “Time-based descent” toggle you can switch on for Arcade or Endless (leave it off and the grid moves as you shoot instead of on a clock). Zen never descends.',
  ] },
  { date: '2026-06-30', title: 'Walls, taps & rotation', items: [
    'New: Asteroids & Bubble Pop — a 🎮 Controls button (top-right) shows how to play (keyboard, mouse, touch) any time, even mid-game; and the Play button is now bigger and always reachable.',
    'New: a CHALLENGE badge on game tiles — when a game is the focus of today’s daily or this week’s weekly challenge, its tile is marked so you can spot it at a glance, with a matching CHALLENGE filter to show just those games.',
    'Improved: search now matches a game’s labels too — type “challenge”, “popular”, “new” or “updated” to see just those games.',
    'New: Bubble Pop — a redesigned start menu. Pick your mode from cards (Arcade / Speedrun / Endless / Zen) that show what each one plays like, with a little icon and your best score; the whole menu is keyboard-friendly, pause works the same from Esc or the ⏸ button, and hitting Menu mid-game asks before it drops your run.',
    'New: Asteroids — a redesigned start menu. Pick your mode from cards (Classic / Classic+) that show what each one plays like and your best score, flip on Speedrun with a tick, and steer the whole menu with the keyboard. Hitting Menu mid-run now asks before it drops your run, and your picks live in the link so you can share the exact setup.',
    'Fix: Asteroids & Asteroids+ — in Speedrun mode your shared/Discord result now leads with your clear time (the actual goal), instead of your score and wave.',
    'Improved: offline play — open komyo once online and every game is saved to play offline (even ones you haven’t opened yet), and refreshing with no connection no longer breaks the app. Try it in airplane mode!',
    'New: Bubble Pop — the play area now has real walls and a ceiling, in both portrait and landscape. Shots bounce off the side walls and stick to the top, and on wide screens the bubbles sit in a centered column.',
    'Fix: Bubble Pop — on phones, tapping a new spot now shoots there. Before, a fresh tap could still fire at wherever you last aimed.',
    'New: Neon Snake — on phones, drag the ↕ handle in the board’s corner to slide the playfield up or down to a comfier spot. It’s remembered next time.',
    'Fix: installed games now respect your phone’s rotation lock — if you’ve turned auto-rotate off, the app stays put instead of spinning. (Reinstall the game to pick this up.)',
  ] },
  { date: '2026-06-29', title: 'Polish & fixes', items: [
    'New: Asteroids+ — a big rebalance. It’s now a finite run that ends with a two-boss finale on wave 30 (beat it for a Victory), upgrades are gentler and now lapse after a few waves so you keep choosing, and a new red kamikaze enemy (from wave 6) charges in and explodes — don’t pop it in your face.',
    'New: Asteroids+ — light aim assist: shots that just graze an enemy curve in and connect.',
    'Improved: Asteroids+ — your ship is now a bright white so it never gets lost among the asteroids, bosses can return fire as far as you can shoot, and pickups are tuned so a good run is rewarded without burying you in power-ups.',
    'New: Meadow Flyer — long runs no longer level off. Past a score of 55 the world speeds up, peaking around 100, so a great run stays a real challenge.',
    'Fix: on narrow phones the top bar no longer crowds itself — the Menu button and the sound/pause buttons keep clear of each other.',
    'Fix: the ‹ Menu button now only shows while you’re actually playing, not on a game’s own menu (where it was easy to mistake for “back to the website”).',
    'Fix: Range — on phones the shot marker now stays exactly where you fired, instead of drifting along with your finger.',
    'Fix: Bubble Pop — the grid now keeps its shape when a new row drops in (no more sideways jump), and your shot sticks to the spot you aimed at instead of occasionally slipping behind the pack.',
    'Improved: Bubble Pop — bubbles render crisp and sharp on high-resolution screens.',
    'Improved: the Filter panel’s Highlights and Genres are now tappable chips (matching the Type buttons) instead of checkboxes — and the panel can be resized.',
    'New: you can now embed the whole arcade on your site, not just a single game (menu → “Embed a game”).',
    'New: direct links to the menu pages — e.g. komyo.online/?m=faq or ?m=changelog open straight to that panel.',
    'New: a quick “?” tip in the search box — search by game name or genre (arcade, puzzle, kids…).',
    'Improved: score posts in our Discord now show a tidy “▶ Play this game on Komyo” link instead of a long raw address.',
    'Fix: completed challenges now reliably show up in your History — even if you finished one inside a game and didn’t reopen the home page that day.',
    'New: Keep Defender — pick a difficulty (Easy / Medium / Hard) on the start screen. Tougher levels make enemies tankier (health now compounds each wave) and tighten your gold, so it stays a real fight.',
    'New: Keep Defender — set each tower’s targeting priority (First / Last / Strongest / Weakest / Closest) from its panel.',
    'Improved: Keep Defender — your shared/Discord result now shows your Score as well as waves survived (so a tougher difficulty actually reads as the bigger run it is).',
  ] },
  { date: '2026-06-28', title: 'Challenges, score cards & more', items: [
    'New: game tiles now show up to three genre tags, each in its own consistent color, and you can filter by any of them.',
    'New: a stack of fresh games is on the way — peek the "coming soon" tiles for what we’re building next.',
    'Fix: Keep Defender — the castle and path no longer clip off the screen edge, and the board clears the score bar.',
    'Fix: Bubble Pop — in landscape on phones the starting bubbles no longer crowd the launcher.',
    'Fix: Asteroids+ — the boss no longer overlaps the score bar on phone screens.',
    'New: Asteroids+ — the roguelite Asteroids (XP, upgrades, bosses, a wave shop) is now its own game. Plain Asteroids is the classic arcade one. Pick your mode right inside each game.',
    'New: Daily & Weekly Challenges — tap 🏆 for today’s challenge plus a bigger weekly one. Earn points (1 per daily, 5 per weekly) that only ever go up, with a History list of everything you’ve completed (up to a year, "Load more" to go back).',
    'New: Score cards — share a picture of your score from the end screen (📷), straight to your apps.',
    'New: Embed games on your own site or blog — an Embed button in each game’s sound menu, plus "Embed a game" in the main menu.',
    'New: a ⏸ pause button in every game (top-right, next to sound).',
    'New: Export / import your data — back it up or move it between devices, no account needed (in the menu under "Your data").',
    'New: a Compact tile view (button by the filters) so more games fit on screen, plus an FAQ and a Privacy policy in the menu.',
    'New: Neon Snake has on-screen arrow buttons on phones — tap to turn instead of swiping; drag the pad anywhere, or tuck it away (and bring it back) with the ✕ / 🎮 button.',
    'New: Brick Breaker on phones — hold the left or right side of the screen to slide the paddle (instead of dragging).',
    'New: Bubble Pop modes — Arcade and Endless now build pressure as you shoot rather than on a clock, with a new Speedrun mode that keeps the timer. Your loaded bubble also auto-swaps if its color is no longer on the board.',
    'Fix: games now re-fit correctly when you rotate your phone between portrait and landscape — Stack stays centered, Brick Breaker keeps room to react, Bubble Pop sticks to portrait on phones, Tower Defense’s menu and keep fit the screen, Asteroids’ end screen fits in landscape.',
    'Fix: Brick Breaker — the paddle now moves instantly and stops the moment you let go; in portrait the top bricks no longer hide under the score bar.',
    'Fix: Brick Breaker — the paddle waits centered until you launch, and the on-screen ◀ ▶ move hints now show in portrait too (not just landscape).',
    'Fix: Asteroids & Asteroids+ — a mode is preselected so Play works right away, and picking a mode now works on phones.',
    'Fix: the Filter panel now fits the screen on phones in landscape — it no longer runs off the edge, and the genre list scrolls.',
    'Fix: Range’s "race to 100" progress bar now tracks targets hit, not points.',
    'Fix: Keep Defender — the upgrade button is greyed out until you can afford it, then pops in.',
  ] },
  { date: '2026-06-27', title: 'We are now Komyo Games', items: [
    'New name & logo: funyo is now Komyo Games — same games, fresh fox mascot.',
    'New: your score auto-posts to our Discord on game-over — now with the game mode + stats (accuracy, level, wave…). Set a display name in the menu, or stay anonymous.',
  ] },
  { date: '2026-06-27', title: 'Home redesign & polish', items: [
    'New: redesigned home page — slide-out menu, instant search and genre filters (your filters now save in the link, so you can bookmark them).',
    'New: NEW and UPDATED badges on game tiles, so fresh and recently-improved games are easy to spot.',
    'New: “Reset all data” to clear your scores, progress and favorites across every game.',
    'New: this changelog 🙂',
    'Fix: Brick Breaker ran too fast on some phones — speed is now consistent everywhere.',
    'Fix: Range “Sprint” is now a proper race to 100 targets.',
  ] },
  { date: '2026-06-26', title: 'First games launch', items: [
    'Added 8 games: Asteroids, Keep Defender, Bubble Pop, Brick Breaker, Stack, Meadow Flyer, Range and Neon Snake.',
  ] },
];
