// Player-facing changelog — newest first. Single source of truth for BOTH the in-page
// 🗒️ Changelog modal (index.html) AND the Discord changelog post: the GitHub Action posts
// only the entries ADDED in a push (diff vs the previous commit), so Discord == this file.
// One release per date: { date:'YYYY-MM-DD', title:'…', items:['New: …','Fix: …'] }.
// Keep bullets plain-language and about what a PLAYER notices — never kit/test/build/refactor.
window.CHANGELOG = [
  { date: '2026-07-01', title: 'Challenges in your games', items: [
    'New: Asteroids & Bubble Pop — a 🏆 Challenges button right in the game shows today’s daily and weekly goals (and gently glows when the game you’re in is the one with a challenge), so you can check the goal without going back to the menu.',
    'New: a back-to-top button on the home page — appears once you’ve scrolled the games list down.',
    'Improved: no more name pop-up when you arrive — you start as anonymous, and set a display name only if you want to (menu → ✏️). One less thing between you and the games.',
    'Changed: Bubble Pop — Speedrun is now a “Time-based descent” toggle you can switch on for Arcade or Endless (leave it off and the grid moves as you shoot instead of on a clock). Zen never descends.',
  ] },
  { date: '2026-06-30', title: 'Walls, taps & rotation', items: [
    'New: Asteroids & Bubble Pop — a 🎮 Controls button (top-right) shows how to play (keyboard, mouse, touch) any time, even mid-game; and the Play button is now bigger and always reachable.',
    'New: a CHALLENGE badge on game tiles — when a game is the focus of today’s daily or this week’s weekly challenge, its tile is marked so you can spot it at a glance, with a matching CHALLENGE filter to show just those games.',
    'Improved: search now matches a game’s labels too — type “challenge”, “popular”, “new” or “updated” to see just those games.',
    'New: Bubble Pop — a redesigned start menu. Pick your mode from cards (Arcade / Speedrun / Endless / Zen) that show what each one plays like, with a little icon and your best score; the whole menu is keyboard-friendly, pause works the same from Esc or the ⏸ button, and hitting Menu mid-game asks before it drops your run.',
    'New: Asteroids — a redesigned start menu. Pick your mode from cards (Classic / Classic+) that show what each one plays like and your best score, flip on Speedrun with a tick, and steer the whole menu with the keyboard. Hitting Menu mid-run now asks before it drops your run, and your picks live in the link so you can share the exact setup.',
    'Fix: Asteroids & Asteroids+ — in Speedrun mode your shared/Discord result now leads with your clear time (the actual goal), instead of your score and wave.',
    'Improved: offline play — open komyo once online and every game is saved to play offline (even ones you haven’t opened yet), and refreshing with no connection no longer breaks the app. Try it in airplane mode!',
    'New: Bubble Pop — the play area now has real walls and a ceiling, in both portrait and landscape. Shots bounce off the side walls and stick to the top, and on wide screens the bubbles sit in a centered column.',
    'Fix: Bubble Pop — on phones, tapping a new spot now shoots there. Before, a fresh tap could still fire at wherever you last aimed.',
    'New: Neon Snake — on phones, drag the ↕ handle in the board’s corner to slide the playfield up or down to a comfier spot. It’s remembered next time.',
    'Fix: installed games now respect your phone’s rotation lock — if you’ve turned auto-rotate off, the app stays put instead of spinning. (Reinstall the game to pick this up.)',
  ] },
  { date: '2026-06-29', title: 'Polish & fixes', items: [
    'New: Asteroids+ — a big rebalance. It’s now a finite run that ends with a two-boss finale on wave 30 (beat it for a Victory), upgrades are gentler and now lapse after a few waves so you keep choosing, and a new red kamikaze enemy (from wave 6) charges in and explodes — don’t pop it in your face.',
    'New: Asteroids+ — light aim assist: shots that just graze an enemy curve in and connect.',
    'Improved: Asteroids+ — your ship is now a bright white so it never gets lost among the asteroids, bosses can return fire as far as you can shoot, and pickups are tuned so a good run is rewarded without burying you in power-ups.',
    'New: Meadow Flyer — long runs no longer level off. Past a score of 55 the world speeds up, peaking around 100, so a great run stays a real challenge.',
    'Fix: on narrow phones the top bar no longer crowds itself — the Menu button and the sound/pause buttons keep clear of each other.',
    'Fix: the ‹ Menu button now only shows while you’re actually playing, not on a game’s own menu (where it was easy to mistake for “back to the website”).',
    'Fix: Range — on phones the shot marker now stays exactly where you fired, instead of drifting along with your finger.',
    'Fix: Bubble Pop — the grid now keeps its shape when a new row drops in (no more sideways jump), and your shot sticks to the spot you aimed at instead of occasionally slipping behind the pack.',
    'Improved: Bubble Pop — bubbles render crisp and sharp on high-resolution screens.',
    'Improved: the Filter panel’s Highlights and Genres are now tappable chips (matching the Type buttons) instead of checkboxes — and the panel can be resized.',
    'New: you can now embed the whole arcade on your site, not just a single game (menu → “Embed a game”).',
    'New: direct links to the menu pages — e.g. komyo.online/?m=faq or ?m=changelog open straight to that panel.',
    'New: a quick “?” tip in the search box — search by game name or genre (arcade, puzzle, kids…).',
    'Improved: score posts in our Discord now show a tidy “▶ Play this game on Komyo” link instead of a long raw address.',
    'Fix: completed challenges now reliably show up in your History — even if you finished one inside a game and didn’t reopen the home page that day.',
    'New: Keep Defender — pick a difficulty (Easy / Medium / Hard) on the start screen. Tougher levels make enemies tankier (health now compounds each wave) and tighten your gold, so it stays a real fight.',
    'New: Keep Defender — set each tower’s targeting priority (First / Last / Strongest / Weakest / Closest) from its panel.',
    'Improved: Keep Defender — your shared/Discord result now shows your Score as well as waves survived (so a tougher difficulty actually reads as the bigger run it is).',
  ] },
  { date: '2026-06-28', title: 'Challenges, score cards & more', items: [
    'New: game tiles now show up to three genre tags, each in its own consistent color, and you can filter by any of them.',
    'New: a stack of fresh games is on the way — peek the "coming soon" tiles for what we’re building next.',
    'Fix: Keep Defender — the castle and path no longer clip off the screen edge, and the board clears the score bar.',
    'Fix: Bubble Pop — in landscape on phones the starting bubbles no longer crowd the launcher.',
    'Fix: Asteroids+ — the boss no longer overlaps the score bar on phone screens.',
    'New: Asteroids+ — the roguelite Asteroids (XP, upgrades, bosses, a wave shop) is now its own game. Plain Asteroids is the classic arcade one. Pick your mode right inside each game.',
    'New: Daily & Weekly Challenges — tap 🏆 for today’s challenge plus a bigger weekly one. Earn points (1 per daily, 5 per weekly) that only ever go up, with a History list of everything you’ve completed (up to a year, "Load more" to go back).',
    'New: Score cards — share a picture of your score from the end screen (📷), straight to your apps.',
    'New: Embed games on your own site or blog — an Embed button in each game’s sound menu, plus "Embed a game" in the main menu.',
    'New: a ⏸ pause button in every game (top-right, next to sound).',
    'New: Export / import your data — back it up or move it between devices, no account needed (in the menu under "Your data").',
    'New: a Compact tile view (button by the filters) so more games fit on screen, plus an FAQ and a Privacy policy in the menu.',
    'New: Neon Snake has on-screen arrow buttons on phones — tap to turn instead of swiping; drag the pad anywhere, or tuck it away (and bring it back) with the ✕ / 🎮 button.',
    'New: Brick Breaker on phones — hold the left or right side of the screen to slide the paddle (instead of dragging).',
    'New: Bubble Pop modes — Arcade and Endless now build pressure as you shoot rather than on a clock, with a new Speedrun mode that keeps the timer. Your loaded bubble also auto-swaps if its color is no longer on the board.',
    'Fix: games now re-fit correctly when you rotate your phone between portrait and landscape — Stack stays centered, Brick Breaker keeps room to react, Bubble Pop sticks to portrait on phones, Tower Defense’s menu and keep fit the screen, Asteroids’ end screen fits in landscape.',
    'Fix: Brick Breaker — the paddle now moves instantly and stops the moment you let go; in portrait the top bricks no longer hide under the score bar.',
    'Fix: Brick Breaker — the paddle waits centered until you launch, and the on-screen ◀ ▶ move hints now show in portrait too (not just landscape).',
    'Fix: Asteroids & Asteroids+ — a mode is preselected so Play works right away, and picking a mode now works on phones.',
    'Fix: the Filter panel now fits the screen on phones in landscape — it no longer runs off the edge, and the genre list scrolls.',
    'Fix: Range’s "race to 100" progress bar now tracks targets hit, not points.',
    'Fix: Keep Defender — the upgrade button is greyed out until you can afford it, then pops in.',
  ] },
  { date: '2026-06-27', title: 'We are now Komyo Games', items: [
    'New name & logo: funyo is now Komyo Games — same games, fresh fox mascot.',
    'New: your score auto-posts to our Discord on game-over — now with the game mode + stats (accuracy, level, wave…). Set a display name in the menu, or stay anonymous.',
  ] },
  { date: '2026-06-27', title: 'Home redesign & polish', items: [
    'New: redesigned home page — slide-out menu, instant search and genre filters (your filters now save in the link, so you can bookmark them).',
    'New: NEW and UPDATED badges on game tiles, so fresh and recently-improved games are easy to spot.',
    'New: “Reset all data” to clear your scores, progress and favorites across every game.',
    'New: this changelog 🙂',
    'Fix: Brick Breaker ran too fast on some phones — speed is now consistent everywhere.',
    'Fix: Range “Sprint” is now a proper race to 100 targets.',
  ] },
  { date: '2026-06-26', title: 'First games launch', items: [
    'Added 8 games: Asteroids, Keep Defender, Bubble Pop, Brick Breaker, Stack, Meadow Flyer, Range and Neon Snake.',
  ] },
];
