// Single source of truth for the arcade catalogue.
// Add a game = drop it in games/<slug>/ and add one entry here.
// `soon: true` renders a greyed, non-clickable "coming soon" tile (the genre tag still shows).
window.GAMES = [
  {
    slug: "asteroids",
    title: "Asteroids",
    blurb: "Fly, shoot, survive. Classic arcade — endless waves plus a speedrun race.",
    icon: "🛸",
    accent: "#9fe8ff",
    tag: "ARCADE",
    added: "2026-06-26",
    updated: "2026-06-28",
  },
  {
    slug: "asteroids-plus",
    title: "Asteroids+",
    blurb: "Roguelite Asteroids — XP, upgrades, bosses and a wave shop. Build a run, survive the waves.",
    icon: "☄️",
    accent: "#b98cff",
    tag: "ROGUELIKE",
    badges: ["pick"],
    added: "2026-06-28",
  },
  {
    slug: "tower-defense",
    title: "Keep Defender",
    blurb: "Hold the path. Build towers, spend gold, defend the keep wave after wave.",
    icon: "🏰",
    accent: "#e0b25a",
    tag: "STRATEGY",
    added: "2026-06-26",
    updated: "2026-06-27",
  },

  {
    slug: "bubbles",
    title: "Bubble Pop",
    blurb: "Shoot glossy soap bubbles to pop matching groups of 3+. Arcade, Speedrun, Endless, and Zen modes with special shots.",
    icon: "🫧",
    accent: "#2ee8c8",
    tag: "PUZZLE",
    added: "2026-06-26",
    updated: "2026-06-28",
  },

  // ---- coming soon ----
  {
    slug: "breakout",
    title: "Brick Breaker",
    blurb: "Bounce the ball, smash every brick. Synthwave neon, power-ups, escalating walls.",
    icon: "🧱",
    accent: "#ff5cc8",
    tag: "ARCADE",
    added: "2026-06-26",
    updated: "2026-06-28",
  },
  {
    slug: "invaders",
    title: "Invaders",
    blurb: "Marching aliens descend on a green CRT. Dodge, shoot, hold the line.",
    icon: "👾",
    accent: "#5fe07a",
    tag: "SHOOTER",
    soon: true,
  },
  {
    slug: "sudoku",
    title: "Sudoku",
    blurb: "Fill the 9×9 grid so every row, column, and box holds 1–9. Easy to expert, with notes and hints.",
    icon: "🔢",
    accent: "#7aa2ff",
    tag: "LOGIC",
    soon: true,
  },
  {
    slug: "crossy",
    title: "Road Hop",
    blurb: "Hop across roads and rivers without getting squished. Blocky and endless.",
    icon: "🐸",
    accent: "#5bb6e0",
    tag: "ARCADE",
    soon: true,
  },
  {
    slug: "stacker",
    title: "Stack",
    blurb: "Time the drop to stack the tower. One tap, pastel-clean, just-one-more.",
    icon: "🧊",
    accent: "#ff9aa2",
    tag: "REFLEX",
    added: "2026-06-26",
    updated: "2026-06-27",
  },
  {
    slug: "icy-tower",
    title: "Icy Tower",
    blurb: "Build speed, leap higher, wall-bounce and chain combos up an endless tower.",
    icon: "🧗",
    accent: "#7fd8ff",
    tag: "PLATFORMER",
    soon: true,
  },
  {
    slug: "pulse-dash",
    title: "Pulse Dash",
    blurb: "Auto-run and jump to the beat — one-tap rhythm platforming through neon gauntlets.",
    icon: "🔺",
    accent: "#caff4d",
    tag: "RHYTHM",
    soon: true,
  },
  {
    slug: "trap-the-cat",
    title: "Trap the Cat",
    blurb: "Wall off the hex board to corner the cat before it slips off the edge.",
    icon: "🐱",
    accent: "#f0a6c8",
    tag: "PUZZLE",
    soon: true,
  },
  {
    slug: "flappy",
    title: "Meadow Flyer",
    blurb: "One-tap flyer through a soft storybook meadow.",
    icon: "🐤",
    accent: "#8fd3a6",
    tag: "CASUAL",
    added: "2026-06-26",
    updated: "2026-06-27",
  },
  {
    slug: "aim-trainer",
    title: "Range",
    blurb: "Flick-aim headshot practice on a tactical range, against the clock.",
    icon: "🎯",
    accent: "#ff7a3c",
    tag: "SKILL",
    added: "2026-06-26",
    updated: "2026-06-27",
  },
  {
    slug: "spellcaster",
    title: "Arcane",
    blurb: "Cast spells against waves of the dark. Runes, sigils, and gold filigree.",
    icon: "🔮",
    accent: "#b98cff",
    tag: "ACTION",
    soon: true,
  },
  {
    slug: "snake",
    title: "Neon Snake",
    blurb: "The classic, in glowing neon. Grow long, don't bite yourself.",
    icon: "🐍",
    accent: "#7fffb0",
    tag: "CLASSIC",
    added: "2026-06-26",
    updated: "2026-06-28",
  },

  // ---- multiplayer (local, single-screen) — coming soon ----
  {
    slug: "tron",
    title: "Light Cycles",
    blurb: "Neon trails fill the arena — box your rivals in, last cycle riding wins. Local 2–4 players.",
    icon: "🏍️",
    accent: "#5fe0ff",
    tag: "ARCADE",
    players: "2–4P",
    mp: true,
    soon: true,
  },
  {
    slug: "air-hockey",
    title: "Air Hockey",
    blurb: "Slam the puck past your friend on a glowing rink. Fast, frantic, two-thumb local play.",
    icon: "🏒",
    accent: "#ff5c8a",
    tag: "SPORT",
    players: "2P",
    mp: true,
    soon: true,
  },
  {
    slug: "slime-volley",
    title: "Slime Volleyball",
    blurb: "Two blobs, one ball, one net — bounce it onto their side. Silly, springy local duel.",
    icon: "🏐",
    accent: "#caff4d",
    tag: "SPORT",
    players: "2P",
    mp: true,
    soon: true,
  },
];
